### ISSUE TITLE
Additions

### ISSUE THREAD

**Issue by maltfield** [thansk/encrypted-email#1]
Thanks for this list. I've in the past been curious about a PGP equivalent to 2fa.directory

## Cryptocurrency

The following websites have PGP keys for communicating with their customers

1. https://flyp.me/
2. https://xchange.me = http://xmxmrjoqo63c5notr2ds2t3pdpsg4ysqqe6e6uu2pycecmjs4ekzpmyd.onion/

It might also be helpful to add the Onion Services links to this repo. Majestic Bank, for example, is majestictfvnfjgo5hqvmuzynak4kjl5tjs3j5zdabawe6n2aaebldad.onion

## Security

BusKill has a PGP key and regularly communicates with customers using PGP

1. https://buskill.in = http://buskillvampfih2iucxhit3qp36i2zzql3u6pmkeafvlxs3tlmot5yad.onion/

Disclosure: I am the founder of the BusKill project.

## Governments

Not sure quite how to say this, but literally every citizen and resident and e-resident of Estonia (including, therefore, every company registered in Estonia) can send encrypted emails.

Everyone in Estonia is issued a [card with a chip confirming to](https://www.id.ee/wp-content/uploads/2020/10/td-id1-chip-app-1.pdf) the European eID (CES TS 15480-2) standard. The software to sign/encrypt & verify/decrypt using the keys stored on the smart card is open-source and the code is available on GitHub

 * https://github.com/open-eid

Obviously, therefore, every government agency and every company registered in Estonia can send cryptographically signed and encrypted email.

## Email Providers

I wonder if we should add email providers who have PGP keys? For example, emails coming from Proton Mail to their customers are certainly encrypted. That's going to be several companies, at least including

1. https://proton.me/
4. https://mail.tutanota.com
5. elude.in = http://eludemailxhnqzfmxehy3bk5guyhlxbunfyhkcksv4gvx6d3wcf6smad.onion/

**Comment by thansk** [comment]
I've added flyp.me and xchange.me.

I can add buskill too, I can see the keys on the bottom but they are timestamped. It'd be nice if there is something more permanent to link to other than the homepage.

Not sure about Estonia, there is generally no reason for anyone outside to communicate with them and I'd assume anyone inside already knows? Also not a method anyone outside of Estonia can easily use. As opposed to for example reporting a vulnerability to the German government.

The email providers I also see no ways to contact with PGP or similar. Proton has a form, Tuta requires payment for email support and it's internal only https://www.reddit.com/r/tutanota/comments/jv5sjo/comment/gchwo4w/?context=3. I don't think they send signed emails outside of their clients and they use special tags for those (Official on Proton and red background on Tuta).

I will consider adding the onion links too.

**Comment by maltfield** [comment]
> BusKill

The full public key is also accessible here:

 * https://www.buskill.in/contact/

> Proton

You can contact Proton Mail at the following address: `contact@proton.me`

Source: https://proton.me/support/zendesk

As the above page states, all contact with the above address will be end-to-end encrypted (with PGP) for proton mail users. For non-proton-mail-users, the PGP key can be obtained from their api/keyserver:

 * https://api.protonmail.ch/pks/lookup?op=get&search=contact@proton.me
