### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by maltfield** [thansk/encrypted-email#2]
Can you please add a LICENSE file to this repo to clarify under which license this information in this repo is released-under?

I recommend [CC BY-SA](https://creativecommons.org/licenses/by-sa/4.0/)

 * https://creativecommons.org/licenses/by-sa/4.0/

**Comment by thansk** [comment]
These are just links, I don't have copyright over links. Everyone is free to click on them and record the same information as is in the repo. I am not adding a license.
